name: 'Auto Roll DEPS'

on: [workflow_dispatch]

jobs:
  deps:
    strategy:
      matrix:
        dep_path:
          - "node/third_party/webnn-polyfill"
          - "node/third_party/webnn-polyfill/test-data"
          - "node/third_party/webnn-samples"
          - "node/third_party/webnn-samples/test-data"
          - "third_party/DirectML"
          - "third_party/gpgmm"
          - "third_party/oneDNN"
          - "third_party/XNNPACK"
          - "third_party/onnxruntime"

    runs-on: windows-2019

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global user.email "webnn-native-autoroll@users.noreply.github.com"
        git config --global user.name "WebNN Native Autoroller"
    - name: Install depot_tools
      shell: cmd
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ..\depot_tools
        set "PATH=%CD%\..\depot_tools;%PATH%"
        gclient
    - uses: actions/checkout@v3
    - name: Sync code for main branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        copy scripts\standalone.gclient .gclient
        gclient sync
    - name: Roll ${{ matrix.dep_path }}
      id: roll_dep
      shell: cmd
      continue-on-error: true
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        roll-dep --no-log ${{ matrix.dep_path }}
    - name: Create Pull Request
      if: steps.roll_dep.outcome == 'success'
      uses: peter-evans/create-pull-request@v4
      with:
        title: Roll ${{ matrix.dep_path }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        branch: autoroller/roll
        branch-suffix: short-commit-hash
        delete-branch: true
        labels: automerge