name: DirectMLX backend (Windows)

on: [push, pull_request]

jobs:

  job:

    runs-on: [self-hosted, Windows, X64, gpu]

    steps:
    - uses: actions/checkout@v2
      with:
        path: update
        fetch-depth: 0

    - name: Update DEPS for update branch
      run: |
        cd update
        (Get-Content -path .\DEPS -Raw) -replace "'checkout_onnxruntime': True", "'checkout_onnxruntime': False" | Set-Content -path .\DEPS
        (Get-Content -path .\DEPS -Raw) -replace "'checkout_samples': True", "'checkout_samples': False" | Set-Content -path .\DEPS

    - name: Sync latest code
      shell: cmd
      run: |
        cd update
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Generate project for update branch
      shell: cmd
      run: |
        cd update
        gn gen out\Release --args="webnn_enable_dmlx=true webnn_enable_wire=true is_debug=false gpgmm_enable_device_checks=true"

    - name: Build for update branch
      shell: cmd
      run: |
        cd update
        ninja -C out\Release

    - name: Test MobileNetV2 for update branch
      shell: cmd
      run: |
        cd update
        echo "Run End2End Tests..."
        out\Release\MobileNetV2.exe -m node\third_party\webnn-polyfill\test-data\models\mobilenetv2_nchw\\weights\ -i examples\images\test.jpg -l nchw -n 201