name: DirectML backend

on: [push, pull_request]

jobs:

  job:

    runs-on: windows-latest

    defaults:
      run:
        working-directory: workflow_scripts

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '14.x'

    - name: Setup
      run: npm install

    - name: Run test by DML backend
      run: npm run test-dml
