name: MLAS backend (Windows)

on: [push, pull_request]

jobs:

  job:
    runs-on: windows-2019

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Install depot_tools
      shell: cmd
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ..\depot_tools
        set "PATH=%CD%\..\depot_tools;%PATH%"
        gclient

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - uses: actions/checkout@v2
      with:
        path: update
        fetch-depth: 0

    - name: Update DEPS for update branch
      shell: pwsh
      run: |
        cd update
        (Get-Content -path .\DEPS -Raw) -replace "'checkout_samples': True", "'checkout_samples': False" | Set-Content -path .\DEPS

    - name: Sync latest code
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Build MLAS library
      run: |
        cd update\third_party\onnxruntime
        .\build.bat --config Release --parallel --enable_msvc_static_runtime

    - name: Generate project for update branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        gn gen out\Release --args="webnn_enable_mlas=true is_debug=false"

    - name: Build for update branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd update
        ninja -C out\Release